Server:
  port: 8087

spring:
  application:
    name: movies-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb

  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8082/realms/digitalmedia
        registration:
          api-movies-service:
            provider: keycloak-provider
            client-id: microservicios
            client-secret: CSMBDFgT5irvBDQDDaFDFBAfd3n4QcrI
            authorization-grant-type:
            redirect-uri: http://localhost:8084/*

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

eureka:
  client:
    enabled: false